#message configuration files
configMessage: config/message.txt
configList: config/list.txt
testList: config/test.txt
testMessage: config/testMessage.txt
#sleep configuration in seconds
loadSleep: 15
shortSleep: 1
longSleep: 2

#some messages
welcomeEvent: WELCOME
errorMessage: HI! I HAVE PROBLEMNS TO REPLY NOW! PLEASE TRY LATER
stopContact: Stop

#conversation id generation config
conversationDateFormat: '%d%m%Y_%H%M%S'
conversationIdPrefix: c
conversationIdSeparator: _
#interval in minutes
conversationInterval: 20

#conversation-api configuration
baseURL: http://localhost:8080
apiVersion: v1
apiUser: api
apiPass: api123
defaultLanguage: pt-BR
httpHeaders: "{'Content-type': 'application/json', 'Accept': 'application/json'}"
sendMessageURL: '{baseURL}/conversation-api/api/{version}/conversation/talk'
sendEventURL: '{baseURL}/conversation-api/api/{version}/conversation/event'
simpleMessageTemplate: '{"language": "{language}", "text": "{text}"}'
continuousMessageTemplate: '{"conversationId": "{conversationId}", "language": "{language}", "text": "{text}"}'
simpleEventTemplate: '{"language": "{language}", "event": "{event}"}'
continuousEventTemplate: '{"conversationId": "{conversationId}", "language": "{language}", "event": "{event}"}'

#whatsapp web configuration
lang: pt-br
data_dir: temp/
whatsapp_url: https://web.whatsapp.com
#class name of the whatsappweb input fields (filter + message)
inputChatClass: _3FRCZ
nonReadChatClass: _31gEB
#xpath to find main participant list object (left side)
#xPathForLefPane: //div[@class='_1qDvT _3R02z']
xPathForLefPane: //div[@id='side']
xPathForConversation: .//*[contains(@aria-label,'Lista de conversas.')]
#Xpath used to find the right conversation (. is used for sub-element)
xPathForNonRead: ./../../../..//span[contains(@aria-label,'lida')]
xPathForChat: .//span[@title='{name}']
#bug finding any other chat if uses for xPathForChat
xPathForListener: .//span[contains(@title,'{name}')]
#XPATH to find chat, improved to use partial name and not full name (not working)
#xPathForChat: .//span[contains(@title,'{name}')]//parent::div[@class='_210SC']
#xpath to fin the button
xPathForSendBtn: //span[@data-icon='send']
xPathForMessagesDiv: //div[@class='z_tTQ' and contains(@aria-label,'Lista de mensagens')]
#copyable-text before footer <footer tabindex="-1" class="_2vJ01">
xPathForLastestMessages: //footer[@class='_2vJ01]//preceding::div[@class='copyable-text']
#<div class="copyable-text" data-pre-plain-text="[07:32, 27/07/2020] Irmao Ramiro: "> ##TODO remove hardcode data
xPathForMessages: ".//*[contains(@data-pre-plain-text, '{today}')]"


##Notes -- xpath expressions examples
##CHAINGED DECLARATION (https://www.swtestacademy.com/xpath-selenium/)
#//div[@class=’form-group’]//input[@id=’user-message’]
##OR AND AND FOR CLASS PATH
#//*[@id=’user-message’ and @class=’form-control’]

##Finding text
#Example: .//label[text()=’Enter message’]
#class="_3ko75 _5h6Y_ _3Whw5"

#Format parse text and time TODO://AUTO-READ
##Message box (after click the name ==> Title)
#<div tabindex="-1" class="z_tTQ" data-tab="2" role="region" aria-label="Lista de mensagens. Pressione a seta para direita em uma mensagem para abrir o menu da mensagem."><div class="_2hqOq _2qhWD focusable-list-item" tabindex="-1">
##inside this there is the text